
project_id = "wzbdqywdnilosyqbndbv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[[fetch.endpoints]]
handler = "v1/download-app"
url = "/api/download-app"

[[fetch.endpoints]]
handler = "v1/get-total-downloads"
url = "/api/get-total-downloads"

[[fetch.endpoints]]
handler = "v1/admin-upload"
url = "/api/admin-upload"
