// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzbdqywdnilosyqbndbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6YmRxeXdkbmlsb3N5cWJuZGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjEzMDAsImV4cCI6MjA2MDYzNzMwMH0.ODGiNd2uUZ6KK7ENN3z_bRlqDC3umfknGbE61UUltFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);