// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mujsmbcfxnvtvnuarxte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11anNtYmNmeG52dHZudWFyeHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzY3NzksImV4cCI6MjA1ODY1Mjc3OX0.t-GVMwaHeGDcmwHJpAg-UPF8vsQDCKNgrciEQ6qcZg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);